name: Release Gate

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    name: Run Release Workflow
    needs: [test]
    uses: ./.github/workflows/release.yml
    secrets: inherit
